name: Manual Image Build to Supervisely Docker

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Docker Image Tag"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo ${{ github.event.inputs.tag_version }}
        run: echo ${{ github.event.inputs.tag_version }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME_COMMUNITY }}
          password: ${{ secrets.DOCKER_TOKEN_COMMUNITY }}

      - name: Login to Docker Supervisely Enterprise
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_ENTERPRISE_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME_ENTERPRISE }}
          password: ${{ secrets.DOCKER_PASSWORD_ENTERPRISE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            supervisely/image-metadata-reader:${{ github.event.inputs.tag_version }}
            ${{ secrets.DOCKER_ENTERPRISE_REGISTRY }}/supervisely-enterprise/ecosystem-apps/image-metadata-reader:${{ github.event.inputs.tag_version }}
          cache-from: type=registry,ref=supervisely/image-metadata-reader:cache
          cache-to: type=registry,ref=supervisely/image-metadata-reader:cache,mode=max
